name: Trigger docs build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      env:
        DOCS_TOKEN: ${{ secrets.DOCS_TOKEN }}
      run: |
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $DOCS_TOKEN" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/geogebra/docs/actions/workflows/antora.yml/dispatches \
        -d '{"ref":"main"}'
